# Generated by Django 6.0.7 on 2026-07-27 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='inspection_notes',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='return_image',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='return_reason',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, help_text='Allow 80% upfront deposit with remainder due upon delivery.'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_brand_tag',
            field=models.CharField(blank=True, help_text='Confidential Brand/Supplier Tag (Visible ONLY to CEO, Manager, and Finance)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='partial_deposit_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Upfront percentage required if partial payment is enabled (e.g. 80).'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='amount_billed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('partial', 'Partial Payment Invoice (80%)'), ('full', 'Full Payment Invoice (100%)'), ('balance', 'Balance Settlement Invoice')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='balance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full 100% Payment'), ('partial', 'Partial 80% Deposit')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeinvoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='store.storeorder'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('partial_payment_submitted', 'Partial Payment (80%) Submitted'), ('partial_payment_confirmed', 'Partial Payment Confirmed by Finance'), ('full_payment_submitted', 'Full Balance Payment Submitted'), ('full_payment_confirmed', 'Full Payment Confirmed by Finance'), ('order_ready', 'Order Ready for Dispatch'), ('picked_up', 'Picked Up by Rider'), ('arrived_at_customer', 'Arrived at Customer Location (Rider Locked)'), ('balance_paid', 'Balance Paid by Customer'), ('delivered', 'Delivered (Snap & Confirm Closed)'), ('completed', 'Completed'), ('return_requested', 'Return/Replacement Requested'), ('returned_to_store', 'Arrived at Store for Inspection'), ('replaced', 'Item Replaced')], default='pending_payment', max_length=40),
        ),
        migrations.CreateModel(
            name='ActivityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/products/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='store/products/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
