# Generated by Django 6.0.7 on 2026-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active account should be shown to customers.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Input account details for store',
                'verbose_name_plural': 'Input account details for store',
            },
        ),
        migrations.AddField(
            model_name='storeorder',
            name='is_location_live',
            field=models.BooleanField(default=False, verbose_name='Is Rider Location Broadcasting Live'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='items_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='rider_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Rider Live Latitude'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='rider_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Rider Live Longitude'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, help_text='Allow 80% upfront deposit with remainder due upon delivery (for orders >= ₦20,000).'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('partial_payment_submitted', 'Partial Payment (80%) Submitted'), ('partial_payment_confirmed', 'Partial Payment Confirmed by Finance'), ('full_payment_submitted', 'Full Balance / 100% Payment Submitted'), ('full_payment_confirmed', 'Full Payment Confirmed by Finance'), ('order_ready', 'Order Ready for Dispatch'), ('picked_up', 'Picked Up by Rider (Live Tracking Active)'), ('arrived_at_customer', 'Arrived at Customer Location (Rider Locked)'), ('balance_paid', 'Balance Paid by Customer'), ('delivered', 'Delivered (Snap & Confirm Closed)'), ('completed', 'Completed'), ('return_requested', 'Return/Replacement Requested'), ('returned_to_store', 'Arrived at Store for Inspection'), ('replaced', 'Item Replaced')], default='pending_payment', max_length=40),
        ),
    ]
