# Generated by Django 6.0.7 on 2026-08-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_deliverymovementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Christmas, Black Friday, Anniversary Sale', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Check to activate this theme globally across the store interface.')),
                ('background_color', models.CharField(default='#111111', help_text='Hex or CSS color for header/background theme (e.g. #cc0001)', max_length=50)),
                ('accent_color', models.CharField(default='#ffc107', help_text='Hex or CSS color for badges/highlights', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard discounted price on normal days', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special promotional/celebration price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original Regular Price', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_theme',
            field=models.ForeignKey(blank=True, help_text='Optional celebration event association', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_products', to='store.promotheme'),
        ),
    ]
