# Generated by Django 6.0.7 on 2026-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_promotheme_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotheme',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Hex or CSS color for text/write-ups under this theme', max_length=50),
        ),
    ]
