# Generated by Django 6.0.7 on 2026-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_useraddressbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial_payment_threshold', models.DecimalField(decimal_places=2, default=20000.0, help_text='Minimum order total required to trigger partial payment option (default: ₦20,000)', max_digits=12)),
                ('default_deposit_percentage', models.PositiveIntegerField(default=80, help_text='Global default deposit percentage required for large items (e.g., 80%)')),
                ('shipping_fee_below_threshold', models.DecimalField(decimal_places=2, default=3000.0, help_text='Flat shipping fee for orders below the threshold', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='visual_search_tag',
            field=models.CharField(blank=True, help_text='Keywords for photo/visual search indexing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, help_text='Allow upfront deposit with remainder due upon delivery for qualifying orders.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_brand_tag',
            field=models.CharField(blank=True, help_text='Confidential Brand/Supplier Tag (Visible ONLY to CEO, General Manager, Manager, and Finance)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('partial', 'Partial Payment Invoice'), ('full', 'Full Payment Invoice (100%)'), ('balance', 'Balance Settlement Invoice')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full 100% Payment'), ('partial', 'Partial Deposit')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('partial_payment_submitted', 'Partial Payment Submitted'), ('partial_payment_confirmed', 'Partial Payment Confirmed by Finance'), ('full_payment_submitted', 'Full Balance / 100% Payment Submitted'), ('full_payment_confirmed', 'Full Payment Confirmed by Finance'), ('order_ready', 'Order Ready for Dispatch'), ('picked_up', 'Picked Up by Rider (Live Tracking Active)'), ('arrived_at_customer', 'Arrived at Customer Location (Rider Locked)'), ('balance_paid', 'Balance Paid by Customer'), ('delivered', 'Delivered (Snap & Confirm Closed)'), ('completed', 'Completed'), ('return_requested', 'Return/Replacement Requested'), ('returned_to_store', 'Arrived at Store for Inspection'), ('replaced', 'Item Replaced')], default='pending_payment', max_length=40),
        ),
    ]
