# Generated by Django 6.0.7 on 2026-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storeglobalsetting_vat_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeglobalsetting',
            name='store_address',
            field=models.TextField(default='Port Harcourt, Nigeria', help_text='Official physical business address shown on invoices'),
        ),
        migrations.AddField(
            model_name='storeglobalsetting',
            name='store_email',
            field=models.EmailField(default='support@technic.com.ng', help_text='Official business support email shown on invoices', max_length=254),
        ),
        migrations.AddField(
            model_name='storeglobalsetting',
            name='store_phone',
            field=models.CharField(blank=True, help_text='Official business contact phone number shown on invoices', max_length=30, null=True),
        ),
    ]
