# Generated by Django 6.0.7 on 2026-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_storeglobalsetting_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Confidential warehouse vendor stock cost. Visible ONLY to Stock Keeper, Finance, General Manager & CEO.', max_digits=12),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='vendor_cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost amount sent or owed to the vendor/supplier for items in this order.', max_digits=12),
        ),
    ]
