# Generated by Django 6.0.7 on 2026-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_vendor_price_storeorder_vendor_cost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderitem',
            name='vendor_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
