# Generated by Django 6.0.7 on 2026-08-09 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_storeorderitem_vendor_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.CharField(help_text='Reason description selectable by customers during a return/refund', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Detailed explanation of the issue with the goods')),
                ('image_1', models.ImageField(upload_to='store/returns/images/')),
                ('image_2', models.ImageField(upload_to='store/returns/images/')),
                ('image_3', models.ImageField(upload_to='store/returns/images/')),
                ('video_proof', models.FileField(help_text='Required video showing proof of issue', upload_to='store/returns/videos/')),
                ('status', models.CharField(choices=[('pending_management_approval', 'Pending Management Approval'), ('rider_assigned', 'Rider Assigned for Pickup'), ('going_to_site', 'Rider Going to Site for Pickup'), ('picked_up', 'Rider Picked Up Goods'), ('delivered_to_store', 'Delivered to Store (Pending Inspection)'), ('approved_pending_finance', 'Approved by Management (Pending Finance Refund)'), ('refunded_and_closed', 'Refund Executed by Finance (Closed)'), ('rejected_and_closed', 'Rejected by Management (Closed)')], default='pending_management_approval', max_length=50)),
                ('rider_status', models.CharField(choices=[('none', 'Not Assigned'), ('going_to_site', 'Going to site for pickup'), ('picked_up', 'Picked up'), ('delivered_to_store', 'Delivered to store')], default='none', max_length=30)),
                ('inspection_notes', models.TextField(blank=True, help_text='Notes from management physical store inspection', null=True)),
                ('rejection_reason_note', models.TextField(blank=True, help_text='Reason why refund was rejected', null=True)),
                ('rejection_proof_file', models.FileField(blank=True, help_text='Optional PDF or image proof for rejection', null=True, upload_to='store/returns/rejections/')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Exact amount refunded by finance', max_digits=12)),
                ('refund_invoice', models.FileField(blank=True, help_text='Refund invoice PDF or image uploaded by finance', null=True, upload_to='store/returns/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_return_pickups', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_returns', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='store.storeorder')),
                ('reason', models.ForeignKey(help_text='Reason selected from CEO dropdown list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.refundreason')),
                ('refund_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
