# Generated by Django 6.0.7 on 2026-08-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_storereturnpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_return', models.PositiveIntegerField(default=1)),
                ('refund_item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeorderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='store.storereturnrequest')),
            ],
        ),
    ]
