# Generated by Django 6.0.7 on 2026-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_user_description_user_narration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TechsNi Services', max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Call Number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Official Contact Email')),
                ('google_email_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Google Gmail Address')),
                ('google_app_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google App Password / Secret Code')),
                ('about_text', models.TextField(blank=True, null=True, verbose_name='About Us Text')),
                ('about_pdf', models.FileField(blank=True, null=True, upload_to='site/about/', verbose_name='About Us PDF Document')),
                ('policy_text', models.TextField(blank=True, null=True, verbose_name='Company Policy Text')),
                ('policy_pdf', models.FileField(blank=True, null=True, upload_to='site/policies/', verbose_name='Company Policy PDF Document')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Number'),
        ),
    ]
