# Generated by Django 6.0.7 on 2026-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_jobtype_alter_job_condition_alter_job_model_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/pdfs/', verbose_name='Upload Invoice PDF'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Discount (₦)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='quotations/pdfs/', verbose_name='Upload Quote PDF'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Until Date'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='VAT / Tax (₦)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='account_name',
            field=models.CharField(blank=True, default='TechsNi Global Services', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='account_number',
            field=models.CharField(blank=True, default='0123456789', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bank_name',
            field=models.CharField(blank=True, default='Wema Bank / First Bank', max_length=100, null=True),
        ),
    ]
