# Generated by Django 6.0.7 on 2026-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_invoice_invoice_pdf_quotation_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJobArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=150)),
                ('assigned_staff', models.CharField(blank=True, max_length=150, null=True)),
                ('job_description', models.TextField()),
                ('job_flow_status', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('has_quotation', models.BooleanField(default=False)),
                ('job_day', models.CharField(max_length=20)),
                ('job_month', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
