# Generated by Django 6.0.7 on 2026-07-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicejobarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_text', models.TextField(default='Welcome to TechsNi Portal...')),
                ('company_policy_pdf', models.FileField(blank=True, help_text='Upload CEO / Admin Company Policy PDF', null=True, upload_to='policies/')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Catalog Title (e.g., How to Register)')),
                ('description', models.TextField(verbose_name='Detailed Instruction Write-up')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructions/images/', verbose_name='Catalog Display Image')),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='instructions/pdfs/', verbose_name='Instruction Unique PDF')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
