# Generated by Django 6.0.7 on 2026-07-28 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_companyinfo_instructioncatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('general_manager', 'General Manager'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('finance', 'Finance Team'), ('worker', 'Worker'), ('customer', 'Customer'), ('marketer', 'Marketer')], default='customer', max_length=30),
        ),
        migrations.CreateModel(
            name='MarketerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
