# Generated by Django 6.0.7 on 2026-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Default Global Commission Percentage (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Custom Commission Percentage (%)'),
        ),
    ]
