# Generated by Django 6.0.7 on 2026-07-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_siteconfiguration_commission_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active account should be shown on invoices and quotations.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Bank Account',
                'verbose_name_plural': 'Service Bank Accounts',
            },
        ),
    ]
