# Generated by Django 6.0.7 on 2026-08-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_companybankaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='job',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/images/'),
        ),
    ]
