# Generated by Django 6.0.7 on 2026-08-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_invoice_discount_amount_invoice_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Office Address'),
        ),
    ]
