# Generated by Django 6.0.7 on 2026-08-04 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_siteconfiguration_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('general_manager', 'General Manager'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('customer_service', 'Customer Service Representative'), ('worker', 'Worker'), ('customer', 'Customer'), ('marketer', 'Marketer')], default='customer', max_length=30),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_source', models.CharField(choices=[('service', 'Service Portal'), ('store', 'Store App')], default='service', max_length=20, verbose_name='App Origin')),
                ('subject', models.CharField(max_length=200, verbose_name='Inquiry Subject')),
                ('status', models.CharField(choices=[('bot_active', 'Handling by AI Bot'), ('pending_agent', 'Waiting for CSR'), ('in_progress', 'Claimed / In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='bot_active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'customer_service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('bot', 'AI Bot'), ('agent', 'Customer Service Rep')], max_length=20)),
                ('message', models.TextField(verbose_name='Message Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='services.supportticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=5, verbose_name='Rating Score (1-5)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Customer Feedback Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'customer_service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_ratings', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='services.supportticket')),
            ],
        ),
    ]
