# Generated by Django 6.0.7 on 2026-08-08 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_user_role_supportticket_ticketmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_document', models.FileField(upload_to='purchase_orders/pdfs/', verbose_name='Attached PO Document (PDF/Image)')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='Payment Term Days (e.g., 30, 60 days)')),
                ('due_date', models.DateField(verbose_name='Calculated PO Due Date')),
                ('approval_status', models.CharField(choices=[('pending_finance', 'Pending Finance Review'), ('pending_executive', 'Pending CEO / GM Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_finance', max_length=30)),
                ('reminder_7day_sent', models.BooleanField(default=False, verbose_name='7-Day Reminder Sent')),
                ('reminder_2day_sent', models.BooleanField(default=False, verbose_name='2-Day Reminder Sent')),
                ('customer_marked_paid', models.BooleanField(default=False, verbose_name='Customer Marked as Paid')),
                ('finance_confirmed_payment', models.BooleanField(default=False, verbose_name='Finance Confirmed Settlement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('executive_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_approved_pos', to=settings.AUTH_USER_MODEL)),
                ('finance_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_approved_pos', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='services.job')),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_pdf', models.FileField(upload_to='statements/pdfs/', verbose_name='Statement of Account PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_statements', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='services.invoice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements_of_account', to='services.job')),
            ],
        ),
    ]
