# Generated by Django 6.0.7 on 2026-08-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_purchaseorderrecord_statementofaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderrecord',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrecord',
            name='payment_terms_days',
        ),
        migrations.AddField(
            model_name='purchaseorderrecord',
            name='payment_terms',
            field=models.CharField(default='Net 30 Days', max_length=100, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='purchaseorderrecord',
            name='status',
            field=models.CharField(choices=[('pending_finance_review', 'Pending Finance Review'), ('pending_executive_approval', 'Pending CEO / GM Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('payment_pending_confirmation', 'Payment Pending Confirmation'), ('settled', 'Settled')], default='pending_finance_review', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Calculated PO Due Date'),
        ),
    ]
