# Generated by Django 6.0.7 on 2026-08-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_purchaseorderrecord_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_po_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quote_sent', 'Quote Sent'), ('quote_approved', 'Quote Approved'), ('quote_rejected', 'Quote Rejected'), ('deposit_paid', 'Deposit Paid'), ('on_site', 'Worker On-Site'), ('in_progress', 'Work in Progress'), ('completed', 'Work Completed'), ('fully_paid', 'Fully Paid & Invoiced'), ('pending_finance_review', 'Pending Finance Review'), ('settled', 'Settled & Closed')], default='pending', max_length=30),
        ),
    ]
