# Generated by Django 6.0.7 on 2026-08-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_job_is_po_job_job_po_number_alter_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount Spent on Overhead / Parts (₦)')),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Remaining Balance (₦)')),
                ('transfer_invoice', models.FileField(blank=True, null=True, upload_to='expenses/invoices/', verbose_name='Transfer Invoice / Receipt (PDF or Image)')),
                ('invoice_number_or_note', models.CharField(blank=True, max_length=150, null=True, verbose_name='Invoice Number or Reference Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_record', to='services.job')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_job_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
