# Generated by Django 6.0.7 on 2026-09-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_jobexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='policy_text',
            field=models.TextField(blank=True, help_text='Company policy text displayed in registration modal', null=True),
        ),
    ]
