# Generated by Django 6.0.7 on 2026-10-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_companyinfo_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='announcement_banner',
            field=models.TextField(blank=True, help_text='Scrolling marquee announcement banner displayed on the login page', null=True),
        ),
    ]
